;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        ghc-sort-lines
        haskell-indentation-delete-backward-char
        haskell-indentation-delete-char
        isearch-abort
        ispell-minor-check
        jump-char-backward
        jump-char-forward
        jump-char-process-char
        jump-char-repeat-backward
        kill-region-or-backward-word
        markdown-exdent-or-delete
        nxml-electric-slash
        org-beginning-of-line
        org-delete-char
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-todo
        orgtbl-self-insert-command
        outline-next-visible-heading
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-kill-region-or-backward-word
        paredit-splice-sexp
        python-indent-electric-colon
        repeat
        sgml-slash
        toggle-input-method
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key-briefly
        ghc-save-buffer
        ))
