;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        haskell-indentation-delete-backward-char
        haskell-indentation-delete-char
        kill-region-or-backward-word
        markdown-exdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-delete-char
        org-self-insert-command
        org-todo
        orgtbl-self-insert-command
        outline-next-visible-heading
        paredit-forward-delete
        paredit-forward-kill-word
        python-indent-electric-colon
        repeat
        sgml-slash
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ghc-save-buffer
        ))
